spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop    # 시작 시 CREATE, 종료 시 DROP


  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    s3:
      endpoint: http://localhost:9000   # MinIO API 주소
      bucket: images                    # 위에서 만든 버킷 이름
    credentials:
      access-key: minioadmin            # MinIO Access Key
      secret-key: minioadmin            # MinIO Secret Key
    region:
      static: us-east-1                 # AWS region처럼 지정 (MinIO는 의미 없음)
    stack:
      auto: false                       # CloudFormation 관련 설정, 꺼도 무방

jwt:
  token:
    access:
      expire-second: 43200
      access-secret: b37d47c4b8aeb3f4ff7e0155f36c4483a224f99861f60aa745abcc1dd4a81484
    refresh:
      expire-second: 2592000
      renewal-interval-second: 50400
      refresh-secret: 46d3bfb7703995bad17525464c2fdd1324ab86cda2b7b836eb0f05dbb5aef970
#  https://jwtsecret.com/generate464c2fdd1324ab86cda2b7b836eb0f05dbb5aef970